-- ST GEORGE COLLEGE SUPABASE DATABASE
-- Run this in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text,
  role text not null default 'learner' check (role in ('learner','staff','admin','SRC')),
  department text,
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  audience text not null default 'all' check (audience in ('all','learners','staff')),
  category text not null default 'General',
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  date date not null,
  title text not null,
  type text not null default 'event' check (type in ('event','holiday','exam')),
  created_at timestamptz not null default now()
);

create table if not exists public.academic_achievements (
  id bigint generated by default as identity primary key,
  title text not null,
  value text not null,
  description text,
  year integer,
  sort_order integer default 0
);

create table if not exists public.school_settings (
  id integer primary key default 1 check (id=1),
  school_name text not null default 'St George College',
  phone text,
  email text,
  address text,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.announcements enable row level security;
alter table public.calendar_events enable row level security;
alter table public.academic_achievements enable row level security;
alter table public.school_settings enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;

-- Profiles: authenticated users can see the directory. Only admins can modify profiles.
drop policy if exists "profiles authenticated read" on public.profiles;
create policy "profiles authenticated read" on public.profiles for select to authenticated using (true);
drop policy if exists "profiles admin write" on public.profiles;
create policy "profiles admin write" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Announcements: authenticated users can read, but audience filtering is also enforced in the frontend.
drop policy if exists "announcements authenticated read" on public.announcements;
create policy "announcements authenticated read" on public.announcements for select to authenticated using (true);
drop policy if exists "announcements admin write" on public.announcements;
create policy "announcements admin write" on public.announcements for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Calendar: members can read; admins can manage.
drop policy if exists "calendar authenticated read" on public.calendar_events;
create policy "calendar authenticated read" on public.calendar_events for select to authenticated using (true);
drop policy if exists "calendar admin write" on public.calendar_events;
create policy "calendar admin write" on public.calendar_events for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Public academic achievements/settings can be read without login; admins manage them.
drop policy if exists "achievements public read" on public.academic_achievements;
create policy "achievements public read" on public.academic_achievements for select to anon,authenticated using (true);
drop policy if exists "achievements admin write" on public.academic_achievements;
create policy "achievements admin write" on public.academic_achievements for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "settings public read" on public.school_settings;
create policy "settings public read" on public.school_settings for select to anon,authenticated using (true);
drop policy if exists "settings admin write" on public.school_settings;
create policy "settings admin write" on public.school_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

do $$
begin
  if not exists (select 1 from public.announcements) then
    insert into public.announcements (title,date,audience,category,text) values
      ('Parent information evening','2026-09-10'::date,'all','Event','Parents and guardians are invited to an information evening at 17:30.'),
      ('Term assessment timetable','2026-09-14'::date,'learners','Academic','The assessment timetable is available from the Academic Office.'),
      ('Inter-school athletics','2026-09-19'::date,'all','Sports','Selected learners will represent St George College.');
  end if;
end $$;

do $$
begin
  if not exists (select 1 from public.calendar_events) then
    insert into public.calendar_events (date,title,type) values
      ('2026-09-10'::date,'Parent information evening','event'),
      ('2026-09-19'::date,'Inter-school athletics','event'),
      ('2026-09-24'::date,'Heritage Day','holiday'),
      ('2026-09-26'::date,'Spring cultural festival','event'),
      ('2026-10-02'::date,'Term assessment begins','exam'),
      ('2026-10-12'::date,'School holiday','holiday'),
      ('2026-10-13'::date,'School holiday','holiday'),
      ('2026-10-14'::date,'School holiday','holiday');
  end if;
end $$;

do $$
begin
  if not exists (select 1 from public.academic_achievements) then
    insert into public.academic_achievements (title,value,description,year,sort_order) values
      ('Circuit position','TOP 1','Replace with the official circuit result.',2026,1),
      ('Geography','BEST SCHOOL','Replace with the official 2026 achievement.',2026,2),
      ('Pass rate','98%','Replace with the verified official pass rate.',2026,3),
      ('Matric results','#1','Replace with the verified official ranking.',2026,4);
  end if;
end $$;

insert into public.school_settings (id) values (1) on conflict (id) do nothing;

-- IMPORTANT: create users in Supabase Authentication -> Users.
-- Then add their matching UUID to profiles. Example:
-- insert into public.profiles (id,name,email,role,department)
-- values ('USER-UUID-HERE','School Administrator','admin@your-school.co.za','admin','Administration');
